# 1.创建多级索引

In [ ]:
import pandas as pd
import numpy as np

# 从元组列表创建
arrays = [['A', 'A', 'B', 'B'], [1, 2, 1, 2]]
tuples = list(zip(*arrays))
index = pd.MultiIndex.from_tuples(tuples, names=['letters', 'numbers'])
df_multi = pd.DataFrame(np.random.randn(4, 2), index=index, columns=['col1', 'col2'])
print(df_multi)

                     col1      col2
letters numbers
A       1        0.231634  1.697774
        2        0.998769  0.658983
B       1       -0.343277 -1.907903
        2        1.375752 -1.242502

In [ ]:
# 从数组创建
arrays = [np.array(['bar', 'bar', 'baz', 'baz']), np.array(['one', 'two', 'one', 'two'])]
df_multi = pd.DataFrame(np.random.randn(4, 2), index=arrays)
print(df_multi)

                0         1
bar one  0.330084  0.374381
    two  0.158894 -0.411017
baz one -0.378045  1.774454
    two  0.194050  1.887619

In [ ]:
# 从DataFrame创建
df_multi = pd.DataFrame({
    'A': ['foo', 'foo', 'bar', 'bar'],
    'B': ['one', 'two', 'one', 'two'],
    'C': [1, 2, 3, 4],
    'D': np.random.randn(4)
})

df_multi = df_multi.set_index(['A', 'B'])
print(df_multi)

         C         D
A   B
foo one  1  1.274787
    two  2 -0.141246
bar one  3 -0.843513
    two  4  2.083471

# 2. 索引基本操作

In [ ]:
import pandas as pd
import numpy as np

df_multi=pd.DataFrame({
    'letters':['A','B','C','D'],
    'numbers':['1','2','3','4'],
    'value': np.random.randn(4)
})
print(df_multi)
df_multi=df_multi.set_index(['letters','numbers'])
print(df_multi)

  letters numbers     value
0       A       1 -0.877854
1       B       2  0.077137
2       C       3  0.013343
3       D       4 -2.426514
                    value
letters numbers
A       1       -0.877854
B       2        0.077137
C       3        0.013343
D       4       -2.426514

In [31]:
print(type(df_multi.index))  
# <class 'pandas.core.indexes.multi.MultiIndex'>

print(df_multi.index.names)  
# ['level1', 'level2']

print(df_multi.index.levels)  
# FrozenList([['A', 'B'], [1, 2]])

<class 'pandas.core.indexes.multi.MultiIndex'>
['letters', 'numbers']
[['A', 'B', 'C', 'D'], ['1', '2', '3', '4']]

In [32]:
# 查看索引属性
print("\n=== 索引属性 ===")
print("索引类型:", type(df_multi.index))
print("索引名称:", df_multi.index.names)
print("索引层级:", df_multi.index.levels)

# 重置索引
print("\n=== 重置索引 ===")
df_reset = df_multi.reset_index()
print(df_reset)

# 交换层级
print("\n=== 交换层级 ===")
df_swapped = df_multi.swaplevel('letters', 'numbers')
print(df_swapped)

# 排序索引
print("\n=== 排序后 ===")
df_sorted = df_multi.sort_index()
print(df_sorted)

=== 索引属性 ===
索引类型: <class 'pandas.core.indexes.multi.MultiIndex'>
索引名称: ['letters', 'numbers']
索引层级: [['A', 'B', 'C', 'D'], ['1', '2', '3', '4']]

=== 重置索引 ===
  letters numbers     value
0       A       1 -0.877854
1       B       2  0.077137
2       C       3  0.013343
3       D       4 -2.426514

=== 交换层级 ===
                    value
numbers letters
1       A       -0.877854
2       B        0.077137
3       C        0.013343
4       D       -2.426514

=== 排序后 ===
                    value
letters numbers
A       1       -0.877854
B       2        0.077137
C       3        0.013343
D       4       -2.426514

# 3.数据选择与切片

In [ ]:
import pandas as pd
import numpy as np

df_multi=pd.DataFrame({
    'letters':['A','B','C','D'],
    'numbers':[1,2,3,4],
    'value': np.random.randn(4),
    'attribute':['big','small','big','small']
})
print(df_multi)
df_multi=df_multi.set_index(['letters','numbers'])
print(df_multi)

  letters  numbers     value attribute
0       A        1 -0.634676       big
1       B        2 -1.508275     small
2       C        3 -2.437759       big
3       D        4 -1.116609     small
                    value attribute
letters numbers
A       1       -0.634676       big
B       2       -1.508275     small
C       3       -2.437759       big
D       4       -1.116609     small

In [ ]:
# 使用xs选择特定层级数据
df_multi.xs('A', level='letters')  # 选择letters层级为'A'的所有数据
df_multi.xs(('A', 1), level=['letters', 'numbers'])  # 选择特定组合

                    value attribute
letters numbers
A       1       -0.634676       big
B       2       -1.508275     small
C       3       -2.437759       big
D       4       -1.116609     small

In [ ]:
# 使用loc进行选择
df_multi.loc['A']  # 选择第一层级为'A'的所有数据
df_multi.loc[('A', 1)]  # 选择特定组合
df_multi.loc[('A', 1):('B', 2)]  # 切片选择

                    value attribute
letters numbers
A       1       -0.634676       big
B       2       -1.508275     small

In [50]:
# 使用pd.IndexSlice进行复杂切片
idx = pd.IndexSlice
df_multi.loc[idx[:, 1], :]  # 选择所有第一层级，第二层级为1的数据
df_multi.loc[idx['A', :], :]  # 选择第一层级为'A'的所有数据
df_multi.loc[idx['A':'B', 1:2], :]  # 范围切片

                    value attribute
letters numbers
A       1       -0.634676       big
B       2       -1.508275     small

In [ ]:
# 选择特定列

print(df_multi.loc[:, 'value'] ) # 选择单列

print(df_multi.loc[:, ['value', 'attribute']] ) # 选择多列

letters  numbers
A        1         -0.634676
B        2         -1.508275
C        3         -2.437759
D        4         -1.116609
Name: value, dtype: float64
                    value attribute
letters numbers
A       1       -0.634676       big
B       2       -1.508275     small
C       3       -2.437759       big
D       4       -1.116609     small

# 4. 数据查询与过滤

In [8]:
import pandas as pd
import numpy as np

df_multi=pd.DataFrame({
    'letters':['A','B','C','D'],
    'numbers':[1,2,3,4],
    'value': np.random.randn(4),
    'attribute':['big','small','big','small']
})
print(df_multi)
df_multi=df_multi.set_index(['letters','numbers'])
print(df_multi)
print(df_multi.index.names)

  letters  numbers     value attribute
0       A        1 -0.311034       big
1       B        2  0.186396     small
2       C        3 -0.839777       big
3       D        4  0.075841     small
                    value attribute
letters numbers
A       1       -0.311034       big
B       2        0.186396     small
C       3       -0.839777       big
D       4        0.075841     small
['letters', 'numbers']

In [9]:
# 按条件过滤
df_multi[df_multi['value'] > 0]  # 普通条件过滤

# 多层级条件查询
mask = (df_multi.index.get_level_values('letters') == 'A') & (df_multi.index.get_level_values('numbers') == 1)
df_multi[mask]

# 使用query方法
df_multi.query('letters == "A" and numbers == 1')

                    value attribute
letters numbers
A       1       -0.311034       big

# 5.数据重塑与转换

In [ ]:
# 堆叠与解堆叠
stacked = df_multi.stack()  # 将列转换为行索引
unstacked = df_multi.unstack()  # 将行索引转换为列
unstacked_level = df_multi.unstack('letters')  # 指定要解堆叠的层级

# 数据透视表
pivoted = df_multi.pivot_table(values='D', index='A', columns='B', aggfunc='mean')

# 数据融合
melted = pd.melt(df_multi, id_vars=['A', 'B'], value_vars=['C', 'D'])

# 6.数据分组与聚合

In [ ]:
# 按层级分组聚合
df_multi.groupby(level='letters').mean()
df_multi.groupby(level=[0, 1]).sum()  # 按索引位置分组

# 多层级分组
df_multi.groupby(['A', 'B']).mean()

# 使用agg进行多种聚合
df_multi.groupby(level='letters').agg({'col1': 'mean', 'col2': 'sum'})

# 使用transform进行分组转换
df_multi['group_mean'] = df_multi.groupby(level='letters')['col1'].transform('mean')

# 7.索引操作与修改

In [ ]:
# 重命名索引层级
df_multi.index = df_multi.index.set_names(['new_name1', 'new_name2'])

# 添加新层级
df_new = df_multi.set_index('new_level', append=True)

# 删除层级
df_dropped = df_multi.droplevel('letters')

# 重组索引
new_index = pd.MultiIndex.from_product([['A', 'B'], [1, 2]], names=['letters', 'numbers'])
df_reindexed = df_multi.reindex(new_index)

# 填充缺失值
df_filled = df_reindexed.fillna(0)

# 8.多级索引计算

In [ ]:
# 跨层级计算
df_multi['new_col'] = df_multi['col1'] + df_multi['col2']

# 分组计算百分比
df_multi['pct'] = df_multi.groupby(level='letters')['col1'].apply(lambda x: x / x.sum())

# 计算层级间差值
df_multi['diff'] = df_multi.groupby(level='letters')['col1'].diff()

# 计算移动平均
df_multi['ma'] = df_multi.groupby(level='letters')['col1'].rolling(window=3).mean().values

# 9.多级索引可视化

In [ ]:
import matplotlib.pyplot as plt

# 按层级分组绘图
df_multi.groupby(level='letters')['col1'].plot(legend=True)
plt.show()

# 解堆叠后绘图
df_multi.unstack('letters')['col1'].plot()
plt.show()

# 热力图
plt.imshow(df_multi.unstack('letters')['col1'], cmap='hot', interpolation='nearest')
plt.show()

# 10. 性能优化技巧

In [ ]:
# 排序索引以提高性能
df_multi = df_multi.sort_index()

# 使用query提高查询性能
result = df_multi.query('letters == "A" and numbers == 1')

# 避免链式赋值
# 不推荐: df.loc[('A', 1)]['col1'] = 100
# 推荐:
df_multi.loc[('A', 1), 'col1'] = 100

# 使用isin进行批量筛选
selected = df_multi[df_multi.index.get_level_values('letters').isin(['A', 'B'])]

# 11. 处理缺失数据

In [ ]:
# 检查缺失值
print(df_multi.isnull().sum())

# 向前填充（按股票分组填充）
df_filled = df_multi.groupby(level='instrument').fillna(method='ffill')

# 删除含有缺失值的行
df_dropped = df_multi.dropna()

# 特定值填充
df_filled = df_multi.fillna(0)

In [61]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
    'B': ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
    'C': np.random.randn(8),
    'D': np.random.randn(8)
})
print(df)
grouped = df.groupby('A')
print(type(grouped))  # <class 'pandas.core.groupby.generic.DataFrameGroupBy'>

     A      B         C         D
0  foo    one  2.023918 -1.675255
1  bar    one -0.799174  0.466369
2  foo    two -0.206851 -0.553889
3  bar  three -1.019713  0.262549
4  foo    two  2.058325 -0.609618
5  bar    two  0.217779 -1.053837
6  foo    one  0.069799  0.662197
7  foo  three -1.083125 -0.287491
<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [62]:
# 查看分组情况
print(grouped.groups)
# 输出：{'bar': [1, 3, 5], 'foo': [0, 2, 4, 6, 7]}

# 获取分组数量
print(grouped.ngroups)  # 2

# 获取分组键
print(grouped.groups.keys())  # dict_keys(['bar', 'foo'])

print(grouped.groups.values())

{'bar': [1, 3, 5], 'foo': [0, 2, 4, 6, 7]}
2
dict_keys(['bar', 'foo'])
dict_values([Index([1, 3, 5], dtype='int64'), Index([0, 2, 4, 6, 7], dtype='int64')])